#!/bin/sh -e

# ---
# RightScript Name: DNS generic update
# Description: >
#   Adds a DHCP hook to update DNS using nsupdate (azure dhcp does not register names in DNS)
#   https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-ddns
# Inputs:
#   DNS_UPDATE_ENABLE:
#     Category: Network
#     Description: Whether to enable the DHCP hook
#     Input Type: single
#     Required: false
#     Advanced: false
#     Default: "text:false"
#     Possible Values: ["text:true", "text:false"]
# Attachments:
# - zz-nsupdate.sh
# ...
#

# Quit if DHCP nsupdate hook is not enabled
if [ "$DNS_UPDATE_ENABLE" != "true" ]; then
    echo "DNS update is not enabled, exiting."
    exit 0
fi

# Copy the DHCP hook into place so DHCP changes will be actioned
sudo cp "$RS_ATTACH_DIR/zz-nsupdate.sh" /etc/dhcp/dhclient-exit-hooks.d/

# Run a DNS update (because this script gets run after the initial DHCP run has happened)
# This replaces the A record with the new IP address.  If we need to add an IP to an existing A record, this script
# will need to have logic to allow it to be used in both scenarios (single IP or potential multiple IPs)
{
    echo "update delete $(hostname -f) a"
    echo "update add $(hostname -f) 900 a $(hostname -i)"
    echo "send"
} | sudo nsupdate -d

echo "DNS update completed"
