#!/bin/bash -e

# ---
# RightScript Name: DNS generic del
# Description: >
#   Uses nsupdate to remove an entry from DNS for the machine's hostname
#   The IP can also be removed from other optional DNS entries
# Inputs:
#   DNS_UPDATE_ENABLE:
#     Category: Network
#     Description: Whether to enable the generic DNS updater
#     Input Type: single
#     Required: false
#     Advanced: false
#     Default: "text:false"
#     Possible Values: ["text:true", "text:false"]
#   DNS_UPDATE_EXTRA_DOMAINS:
#     Category: Network
#     Description: Optional extra domains to update (comma separated)
#     Input Type: single
#     Required: false
#     Advanced: false
#     Default:
# ...
#

# Quit if DHCP nsupdate hook is not enabled
if [ "$DNS_UPDATE_ENABLE" != "true" ]; then
    echo "DNS update is not enabled, exiting."
    exit 0
fi

ip=$(hostname -i)
name=$(hostname -f)
IFS=',' read -ra domains <<< "$DNS_UPDATE_EXTRA_DOMAINS"

echo ">> IP is $ip"
echo ">> Domains are: $name ${domains[@]}"

for domain in $name ${domains[@]}; do
  echo ">> Removing $ip from $domain"
  {
    echo "update del $domain A $ip"
    echo "send"
  } | sudo nsupdate -d
done

echo ">> DNS update completed"
